version: '3'
services:
  geoserver:
    build:
      context: .
      args:
        - GEOSERVER_VERSION=2.26.0
        - CORS_ENABLED=true
        - CORS_ALLOWED_METHODS=GET,POST,PUT,HEAD,OPTIONS
    ports:
      - "${GEOSERVER_PORT}:8080"
    environment:
      - RUN_UNPRIVILEGED=true
      - RUN_WITH_USER_UID=${RUN_WITH_USER_UID}
      - RUN_WITH_USER_GID=${RUN_WITH_USER_GID}
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
      - POSTGRES_JNDI_ENABLED=true
      - POSTGRES_JNDI_RESOURCE_NAME=jdbc/postgres
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGIS_PORT=${POSTGIS_PORT}
      - HTTPS_ENABLED=${HTTPS_ENABLED}
      # - HTTPS_KEYSTORE_FILE=${HTTPS_KEYSTORE_FILE}
      - HTTPS_KEYSTORE_PASSWORD=${HTTPS_KEYSTORE_PASSWORD}
      - HTTPS_KEY_ALIAS=${HTTPS_KEY_ALIAS}
    volumes:
      - ./geoserver_data:/opt/geoserver_data/:Z
      - ./additional_libs:/opt/additional_libs:Z
    healthcheck:
      test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
      interval: 1m
      retries: 3
      timeout: 20s

  postgis:
    image: postgis/postgis:17-3.4-alpine@sha256:5a1dbedac34e0e6663f8b7190d393339571f1cb3ecb2ab2f724524b4f3c7956e
    ports:
      - "${POSTGIS_PORT}:5432"
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgis/postgresql_data:/var/lib/postgresql/data:Z
    healthcheck:
      test: pg_isready -U ${POSTGRES_USERNAME} -h localhost -t 5 || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
